# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0005_auto_20151202_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('founded', models.DateField(null=True)),
                ('dissolved', models.DateField(null=True)),
                ('real', models.BooleanField(default=True)),
                ('defunct', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('international', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
            options={
                'ordering': ('short_name',),
            },
        ),
    ]
