# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
        ('places', '0003_auto_20151202_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('short_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('opened', models.DateField(null=True)),
                ('year_opened', models.IntegerField(null=True)),
                ('closed', models.DateField(null=True)),
                ('year_closed', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('width', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('measure', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=31, null=True)),
                ('denomination', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('architect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.Bio')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City')),
            ],
        ),
    ]
