# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_teamalias'),
        ('games', '0001_initial'),
        ('bios', '0002_auto_20151202_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minute', models.IntegerField(null=True)),
                ('penalty', models.BooleanField(default=False)),
                ('own_goal', models.BooleanField(default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('own_goal_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_goal_set', to='bios.Bio')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.Bio')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'ordering': ('game', 'minute', 'team'),
            },
        ),
        migrations.AddField(
            model_name='assist',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
        ),
        migrations.AddField(
            model_name='assist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.Bio'),
        ),
    ]
