# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_auto_20151202_1842'),
        ('sources', '0001_initial'),
        ('games', '0001_initial'),
        ('teams', '0002_teamalias'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('goals_for', models.IntegerField(blank=True, null=True)),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('ties', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('games_started', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('own_goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('shots_on_goal', models.IntegerField(blank=True, null=True)),
                ('fouls_committed', models.IntegerField(blank=True, null=True)),
                ('fouls_suffered', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('age', models.FloatField(null=True)),
                ('on', models.IntegerField(null=True)),
                ('off', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('result', models.CharField(max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.Bio')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.Source')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'ordering': ('game', 'order', 'on', '-id'),
            },
        ),
    ]
