# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0002_auto_20151202_1842'),
        ('teams', '0002_teamalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.Bio')),
                ('team_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='teams.Team')),
                ('team_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='teams.Team')),
            ],
        ),
    ]
