# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20151202_0616'),
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='birth_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_set', to='places.Country'),
        ),
        migrations.AddField(
            model_name='bio',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_set', to='places.City'),
        ),
        migrations.AddField(
            model_name='bio',
            name='deathplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='death_set', to='places.City'),
        ),
    ]
