# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=150)),
                ('international', models.BooleanField(default=False)),
                ('ctype', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
