# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after', to='competitions.Competition')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before', to='competitions.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='relationships',
            field=models.ManyToManyField(through='competitions.CompetitionRelationship', to='competitions.Competition'),
        ),
    ]
