# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0002_auto_20151202_1842'),
        ('places', '0005_auto_20151202_0616'),
        ('competitions', '0003_auto_20151202_1821'),
        ('sources', '0001_initial'),
        ('teams', '0002_teamalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=255)),
                ('round', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('starter_count', models.IntegerField(blank=True, null=True)),
                ('goal_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('has_date', models.BooleanField()),
                ('team1_original_name', models.CharField(max_length=255)),
                ('team2_original_name', models.CharField(max_length=255)),
                ('team1_score', models.IntegerField(null=True)),
                ('official_team1_score', models.IntegerField(null=True)),
                ('team2_score', models.IntegerField(null=True)),
                ('official_team2_score', models.IntegerField(null=True)),
                ('team1_result', models.CharField(max_length=5)),
                ('team2_result', models.CharField(max_length=5)),
                ('result_unknown', models.BooleanField(default=False)),
                ('not_played', models.BooleanField(default=False)),
                ('forfeit', models.BooleanField(default=False)),
                ('goals', models.IntegerField()),
                ('minigame', models.BooleanField(default=False)),
                ('indoor', models.BooleanField(default=False)),
                ('minutes', models.IntegerField(default=90)),
                ('neutral', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('merges', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.City')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Country')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.Team')),
                ('linesman1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman1_games', to='bios.Bio')),
                ('linesman2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman2_games', to='bios.Bio')),
                ('linesman3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linesman3_games', to='bios.Bio')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_refereed', to='bios.Bio')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Season')),
                ('shootout_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='something', to='teams.Team')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='GameSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=1023)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='sources',
            field=models.ManyToManyField(through='games.GameSource', to='sources.Source'),
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Stadium'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1_games', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2_games', to='teams.Team'),
        ),
    ]
