# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('author', models.CharField(max_length=1023)),
                ('games', models.IntegerField(null=True)),
                ('stats', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SourceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1023)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Source')),
            ],
        ),
    ]
